name: lingyun_widget
description: LingYun Widgets.
version: 0.0.3
homepage: none

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^3.1.1
  another_flushbar: ^1.10.28
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-alpha.png
    - assets/images/lingyun-logo.png
