name: lingyun_widget
description: LingYun Widgets.
version: 0.0.3
author: Gikode <827266641@qq.com>
homepage: none

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^3.1.1
  flushbar:
    git:
      url: git://github.com/prasadsunny1/flushbar
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-alpha.png
    - assets/images/lingyun-logo.png
